// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: c++.capnp

#pragma once

#ifndef CAPNP_bdf87d7bb8304e81_API 
#if defined(_MSC_VER)
#if defined(CAPNP_bdf87d7bb8304e81_EXPORTS)
#define CAPNP_bdf87d7bb8304e81_API  __declspec(dllexport)
#else
#if defined(_LIB)
#define CAPNP_bdf87d7bb8304e81_API 
#else
#define CAPNP_bdf87d7bb8304e81_API  __declspec(dllimport)
#endif
#endif
#else
#define CAPNP_bdf87d7bb8304e81_API 
#endif
#endif
#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA_2(b9c6f99ebf805f2c, CAPNP_bdf87d7bb8304e81_API );
CAPNP_DECLARE_SCHEMA_2(f264a779fef191ce, CAPNP_bdf87d7bb8304e81_API );

}  // namespace schemas
}  // namespace capnp

namespace capnp {
namespace annotations {

// =======================================================================================

// =======================================================================================

}  // namespace
}  // namespace

CAPNP_END_HEADER

